apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-exposer
  labels:
    app: api-exposer
spec:
  selector:
    matchLabels:
      app: api-exposer
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api-exposer
    spec:
      containers:
        - image: carlriis/nginx_exposer_safe_secrets
          imagePullPolicy: Always
          name: nginx-exposer
          env:
            - name: API_URL
              value: "http://encryption-program:8000"
          ports:
            - containerPort: 80
