apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    type: local
    for: redisData
spec:
  storageClassName: standard
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
