apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-apps
  namespace: apps
spec:
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: ClientIP
