apiVersion: v1
kind: Service
metadata:
  labels:
    component: controller
    name: prometheus-operator
  name: prometheus-operator
spec:
  clusterIP: None
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    component: controller
    name: prometheus-operator
