apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-exposer
  labels:
    app: api-exposer
spec:
  selector:
    matchLabels:
      app: api-exposer
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api-exposer
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx-exposer
          env:
            - name: API_URL
              value: "http://encryption-program:8000"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/templates/
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-template-file
---
apiVersion: v1
kind: Service
metadata:
  name: api-exposer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: api-exposer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-template-file
data:
  default.conf.template: |
    server {
      listen 80;
      server_name 192.0.2.0;
      location / {
        proxy_pass ${API_URL}; 
      }
    }
