apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption-program
  labels:
    app: encryption-program
spec:
  selector:
    matchLabels:
      app: encryption-program
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: encryption-program
    spec:
      containers:
        - image: carlriis/flask_app_safe_secrets
          imagePullPolicy: Always
          name: flask-app
          env:
            - name: FLASK_PORT
              value: "8000"
          env:
            - name: MASTERAUTH
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: encryption-program
  name: encryption-program
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: encryption-program